### PR TITLE
PelletierConstructionGroup.github.io_5_ 4_houzz-assets-styles-removal

### LINKED ISSUE #4: Remove houzz assets and css styles: The first 4 files inside the projects folder.
Relates to #2 
As a developer, I want to remove houzz assets and styles from the following files:
projects/
* 6871419-timber-frame-barn.html
* 6871428-mukilteo-house.html
* 6871440-open-concept-kitchen.html
* 6871444-ranch-home-update.html

### PR DESCRIPTION
**Pull request by TuongPhamM**
resolves #4

### CODE REVIEW

**Review by heosman — APPROVED** [review]
The houzz assets and styles have been removed from the first four pages. Will the references to houzz's fonts also be removed?

**Comment by TuongPhamM** [comment]
> The houzz assets and styles have been removed from the first four pages. Will the references to houzz's fonts also be removed
I don't know how clean the removal should be, since there are many houzz referenced components those we want to keep the page content. Do you have any suggestions on what else should be taken off?

**Review by JoyZhang2023 — APPROVED** [review]
Confirmed that houzz logo and links are removed from footer section on all 4 files.

**Review by Seiyaroo — APPROVED** [review]
Things seem to be removed. It's nitpicky but that's a lot of line space between line 3 and 4 haha. 

As for your other question about removal, anything that might break the site visually we should stay with for now, ala fonts, unless we just replace them with defaults like Helvetica or something. That said, it could be done in a different PR!

**Review by taylorpapke — APPROVED** [review]
Looks good to me.

**Pull request merged**
