### PR TITLE
PelletierConstructionGroup.github.io_6_19_Copy-CSS-from-Houzz

### LINKED ISSUE #28: Copy CSS from Houzz: Index and contact pages
relates to #19

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Resolves #28  Copy CSS from Houzz for below pages. 

- [x] projects.html
- [x] testimonials.html
- [x] projects/6871419-timber-frame-barn.html
- [x] projects/6871428-mukilteo-house.html
- [x] projects/6871440-open-concept-kitchen.html
- [x] projects/6871444-ranch-home-update.html
- [x] projects/6871446-bathroom-expansion.html
- [x] projects/6871458-great-wall-of-lake-city.html
- [x] projects/7167797-wrap-around-deck-with-patio-cover.html
- [x] projects/7167805-composite-deck.html
- [x] projects/7167814-modern-porch.html
- [x] projects/7167820-new-shop.html
- [x] projects/7167823-railing.html
- [x] projects/7167828-bathroom.html

This pull request is to extract css from existing Houzz page and add it to our repo so that we can use it with direct link. 1 new css files were add for stylesheet while inline styles are kept. All pages layout remains.

### CODE REVIEW

**Comment by Ali-7s** [comment]
The navbar styling for index.html and the other main pages seems to be different

Index: 
image
Projects: 
image
About: 
image

**Comment by taylorpapke** [comment]
It's more than just the nav bar:
https://pelletierconstructiongroup.com:
Screenshot 2024-05-13 at 2 37 41 AM
PelletierConstructionGroup.github.io/index.html:
Screenshot 2024-05-13 at 2 38 07 AM

**Comment by JoyZhang2023** [comment]
@Ali-7s Thanks for your feedback. Somehow my preview works fine on Home page and other pages. 
Index page:
image

Could you please try now and see if it's fixed?

**Review by Ali-7s — APPROVED** [review]
LGTM!

**Review by heosman — COMMENTED** [review]
Not sure if I'm doing something wrong, but the pages don't have styles on my end, with the most recent pulled changes from the branch. 

image

**Comment by taylorpapke** [comment]
@JoyZhang2023 What is going on with this PR? The pages are looking like @heosman's screenshot on my end as well.

**Comment by JoyZhang2023** [comment]
@heosman @taylorpapke All page render fine on my end. If you open the html directly, the css file couldn't render due to use of relative path link. I'm using Live Preview extension to check the page preview in VS code. Please let me know if it helps.

**Comment by taylorpapke** [comment]
> @heosman @taylorpapke All page render fine on my end. If you open the html directly, the css file couldn't render due to use of relative path link. I'm using Live Preview extension to check the page preview in VS code. Please let me know if it helps.

I downloaded Microsoft Live Preview extension but am still getting the same result. Is there something else I'm missing here?
Screenshot 2024-05-15 at 6 20 24 PM

**Comment by JoyZhang2023** [comment]
> > @heosman @taylorpapke All page render fine on my end. If you open the html directly, the css file couldn't render due to use of relative path link. I'm using Live Preview extension to check the page preview in VS code. Please let me know if it helps.
> 
> I downloaded Microsoft Live Preview extension but am still getting the same result. Is there something else I'm missing here? Screenshot 2024-05-15 at 6 20 24 PM

The preview works fine. Only the code seems off. Could you switch to my branch (copy-css-style-from-houzz) and run the preview again?

**Comment by taylorpapke** [comment]
It is your branch:
Screenshot 2024-05-15 at 9 52 44 PM

**Comment by JoyZhang2023** [comment]
> It is your branch: Screenshot 2024-05-15 at 9 52 44 PM

The same file on my end renders fine. I noticed that the recent commit on your side shows 5 days ago. There're more commits 4 days ago on 5/11/24. Could you check the commit history? There should be 8 commits. If the problem persist, I'm create a new branch to test out. Maybe I used the same branch name which was merged before. 
image

**Comment by taylorpapke** [comment]
Oh, so you just have to push the changes on your branch? That should update this PR.

**Comment by heosman** [comment]
> @heosman @taylorpapke All page render fine on my end. If you open the html directly, the css file couldn't render due to use of relative path link. I'm using Live Preview extension to check the page preview in VS code. Please let me know if it helps.

@JoyZhang2023 I also installed the Microsoft Live Preview Extension and am still experiencing the same problem, like @taylorpapke. I am running the preview from the copy-css-style-from-houzz branch. I noticed from your screenshot that our URLs looks different. Might this be the problem?
image

I removed the "PelletierConstructionGroup.github.io" from the paths to the css files and it seems to be rendering properly now.
image

**Comment by taylorpapke** [comment]
@JoyZhang2023 Yes, please update. Thanks!

**Comment by JoyZhang2023** [comment]
> @JoyZhang2023 Yes, please update. Thanks!

@taylorpapke Got it. Working on it. Give me 20 minutes.

**Comment by JoyZhang2023** [comment]
@heosman @taylorpapke css file paths have been updated on all files. Please check if it renders fine.

**Review by heosman — APPROVED** [review]
All of the pages are rendering properly for me now.

**Review by taylorpapke — APPROVED** [review]
All pages are working properly now

**Pull request merged**
