### PR TITLE
PelletierConstructionGroup-6-40-copy-javascript-from-houzz-testimonialspage

### LINKED ISSUE #40: Copy JavaScript from Houzz: testimonials.html

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #40 
*Updated JavaScript src links in testimonials.html

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
The page appears to still be rendering properly.

**Review by heosman — APPROVED** [review]
LGTM!

**Review by JoyZhang2023 — APPROVED** [review]
LGTM. Page renders fine and all js links have been replaced with local file.

**Review by IsaacJrTypes — APPROVED** [review]
Page renders properly and js files links have been updated. Good job!

**Review by IsaacJrTypes — APPROVED** [review]
Page renders properly with updated javascript files

**Pull request merged**
