### PR TITLE
PelletierConstructionGroup-6-37-copy-javascript-from-houzz-aboutpage

### LINKED ISSUE #38: Copy JavaScript from Houzz: about.html

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #38 
* Updated JavaScript src links in about.html

### CODE REVIEW

**Review by taylorpapke — CHANGES_REQUESTED** [review]
Links look good but page css is rendering funny:
Screenshot 2024-05-13 at 2 59 44 AM

Weird because it looks fine on the main branch.

**Review by Seiyaroo — COMMENTED** [review]
I imagine the breakage is happening due to the change in names. If we fix the name linkage it should fix the overall visual errors happening. That's a guess though not a guarantee.

**Comment by Ali-7s** [comment]
> Links look good but page css is rendering funny: Screenshot 2024-05-13 at 2 59 44 AM
> 
> Weird because it looks fine on the main branch.

I just ran it again and page renders fine for me: 
image

**Review by heosman — APPROVED** [review]
The page looks the same here as on the main branch.

image

**Comment by taylorpapke** [comment]
@heosman @Ali-7s How did you test the page? I am checking out this branch and loading the html in my browser but keep getting the same results.

**Review by JoyZhang2023 — APPROVED** [review]
LGTM. All Houzz js files have been replaced with local script.

**Review by taylorpapke — APPROVED** [review]

**Pull request merged**
