### PR TITLE
PelletierConstructionGroup-6-36-copy-javascript-from-houzz-indexpage

### LINKED ISSUE #36: Copy JavaScript from Houzz: Index.html

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #36 
* Copied over the javascript code from ones linked in the houzz index.html page 
* Updated script src links in index.html

### CODE REVIEW

**Review by heosman — APPROVED** [review]
LGTM! @taylorpapke Will the names for the JS files ever be changed to be more reader-friendly?

**Review by intisarosman1 — APPROVED** [review]
Looks good!

**Review by Seiyaroo — APPROVED** [review]
LGTM -> I agree with the comment on name change of files to make them more user friendly. It will help long term anyways. But let's work a separate PR for that change. Maybe save it for someone low on time this quarter?

**Review by taylorpapke — APPROVED** [review]
Looks good. All the pages are still rendering properly. Yes, we can probably change the names to be more user friendly at some point.

**Pull request merged**
