### PR TITLE
PelletierConstructionGroup.github.io_5_2_removed-houzz-logos-links

### PR DESCRIPTION
**Pull request by larsswenson**
Removed houzz social media logos/links and "created with houzz" logos/links from:
index.html, about.html, contact.html, projects.html, testimonials.html

Restored broken PCG social media logos/links across above files

Removed houzz name from cookies pop-up window

PelletierScreenshot

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Tested this by pulling down your branch for this PR and viewing each html page in my browser. The Houzz logo at the bottom of each page had been deleted. Is there a better way to test this than just opening each page separately? @keiffer213

**Review by TuongPhamM — COMMENTED** [review]
Great work, I think it's easier to review if you can reformat it so it's more readable. I use Prettier extension in VS Code Studio. Find it very useful for everything. I just submitted a PR, you can check to see how I name and describe it. Let me know if you have any questions.

**Comment by Diego-Cano** [comment]
Great update! Prettier works seamlessly with VS Code and other IDEs. Additionally, ESLint as a plugin can enforce code quality standards alongside Prettier. They’re awesome for maintaining clean, readable code and saving time on manual reviews.

For detailed instructions on setting up and configuring Prettier, check out this link: 
https://prettier.io/docs/en/options.html

If you need more plugins to ease the developing process, Webpack can be a handy choice for module bundling, and if you’re working with CSS, PostCSS plugins are super cool to optimize your stylesheets.

**Review by heosman — APPROVED** [review]
The houzz logo and links has been removed from the bottom of all of the pages mentioned. Don't forget to resolve the branch conflict.

**Review by keiffer213 — APPROVED** [review]
Looks great to me! Loading each page had the same result!

Old Footer: 
image


Updated Footer with no houzz logo:
image

**Review by JoyZhang2023 — APPROVED** [review]
all five files work well on local as example image.

**Comment by taylorpapke** [comment]
The conflicts for this PR might be hard to resolve. Are you going to give it a shot or make a new PR?

**Comment by larsswenson** [comment]
> @larsswenson The conflicts for this PR might be hard to resolve. Are you going to give it a shot or make a new PR?

@taylorpapke I'm unsure how to resolve the conflicts or what caused them. What might you recommend?

**Comment by taylorpapke** [comment]
@larsswenson I think this is due to the format of the code changing in the last merge. I don't think this is necessarily a bad thing because it allows for better readability vertically. However, I believe the resulting conflicts that arise with this PR may be too difficult to resolve because of the horizontal length of some of the lines of code. I think the best course of action might just be to redo this PR with a fresh branch from main. 

@bcko Do you know of any better way to handle this?

**Comment by bcko** [comment]
@taylorpapke @larsswenson 

I also agree that the formatting changes improve vertical readability. In order to facilitate better collaboration and maintain consistency in our codebase, I suggest that we standardize our approach to HTML formatting.

It appears that some of the HTML files, like the contact.html on the main branch, have already been processed through an HTML formatter/beautifier. To prevent similar conflicts in the future and streamline our code integration process, I recommend that we apply the same HTML formatter/beautifier to all HTML files across the project. This way, any formatting differences that lead to merge conflicts can be systematically addressed, reducing the overhead on handling such issues manually. This might involve some initial effort to set up, but it will save us time in the long run

**Pull request closed without merging**
