### PR TITLE
pelletierconstructiongroup-6-33-re-remove-houzz-cookies

### PR DESCRIPTION
**Pull request by larsswenson**
New pull request to resolve conflicted previous one. This time also removed cookies modals.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Looks great! Thanks for doing this again!

**Comment by Seiyaroo** [comment]
@taylorpapke @larsswenson How does this compare to #25 ?

**Review by keiffer213 — APPROVED** [review]
These look good! the houzz and cookies were removed! 

@Seiyaroo it seems this one takes out the the houzz and cookie preference links from the main pages while #25 removes them from only the projects folder

image

**Review by Seiyaroo — APPROVED** [review]
LGTM with the comment above :)

**Pull request merged**
