### PR TITLE
Remove Houzz logos  7167814-modern-porch

### PR DESCRIPTION
**Pull request by el-riber**
As a developer my role was to remove all houzz logos

### CODE REVIEW

**Review by taylorpapke — COMMENTED** [review]
The Houzz logos still need to be removed:
Screenshot 2024-04-30 at 9 20 06 PM

**Comment by larsswenson** [comment]
I also still see the houzz logos/links:
PCGScreenshot

**Comment by el-riber** [comment]
I will fix guys…

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by taylorpapke** [comment]
@el-riber This is the same thing that Brad mentioned in your other PR. Can you delete the extra file you created and edit the 7167814-modern-porch.html in the projects folder. Also, we only need to remove the Houzz logos pictured below:
327047433-cd99e5f7-2c99-4776-8272-ae9e64ce1cf7

**Comment by taylorpapke** [comment]
@el-riber I sent you a DM in regard to the closure of this PR. @larsswenson will readdress this in a new PR soon.

**Pull request closed without merging**
