### PR TITLE
PelletierConstructionGroup.github.io_6_19-01_Copy-CSS-from-Houzz

### LINKED ISSUE #19: USER STORY: Copy CSS from Houzz
As a developer, I want to copy over CSS style sheets from Houzz into our Github repo. The first stage is to copy CSS style for below 5 pages.

- [x] about.html
- [x] contact.html
- [x] index.html
- [x] projects.html
- [x] testimonial.html

### LINKED ISSUE #28: Copy CSS from Houzz: Index and contact pages
relates to #19

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Partial resolves #28 Copy CSS from Houzz for below pages. Will continue with more pages when sprint 5 pull requests merged.

- [x] index.html
- [x] contact.html
- [x] about.html

This pull request is to extract css from existing Houzz page and add it to our repo so that we can use it with direct link. 2 new css files were add for stylesheet while inline styles are kept. All pages layout remains.

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
The pages look good. The css files from Houzz have been copied over and internal css styles have been moved into them which is a nice touch. The href links have been diverted from Houzz and redirected to the newly located css files.

**Review by Seiyaroo — APPROVED** [review]
LGTM!

**Review by heosman — APPROVED** [review]
LGTM!

**Review by intisarosman1 — APPROVED** [review]
The pages look good! LGTM

**Review by IsaacJrTypes — APPROVED** [review]
All pages render properly without any css issues. Good job on extracting the css

**Pull request merged**
