### PR TITLE
PelletierConstructionGroup_6_64_copy-project-images

### LINKED ISSUE #64: Images: Copy Projects Images
This issue tackles the following:
1. copy over images for each project into projects/images folder.
2. change references to the images in projects.images folder for the following project pages:
- [x] timber-farm-barn
- [x] mukilteo-house
- [x] open-concept-kitchen
- [x] ranch-home-update
- [x] bathroom-expansion
- [x] great-wall-of-lake-city
- [x] wrap-around-deck-with-patio-cover
- [x] composite-deck
- [x] modern-porch
- [x] new-shop
- [x] railing
- [x] bathroom

### PR DESCRIPTION
**Pull request by taylorpapke**
partially resolves #64 

This PR tackles adding the projects/images folder along with the images for the following project pages:
- timber-frame-barn
- mukilteo-house 
- timber-farm-barn
- mukilteo-house
- open-concept-kitchen
- ranch-home-update
- bathroom-expansion
- great-wall-of-lake-city
- wrap-around-deck-with-patio-cover
- composite-deck
- modern-porch
- new-shop
- railing
- bathroom

I also referenced these newly located image files from the project pages.

### CODE REVIEW

**Comment by taylorpapke** [comment]
Will this file structure work for the images in the projects folder? Most of the files seem to large to view in PR. Also, carousel doesn't seem to scroll through images now. Any idea to what's going on here?

**Review by larsswenson — APPROVED** [review]
A chore, indeed! Images rendered and copied, all 76 of them!

**Review by bcko — APPROVED** [review]
Thank you for working on this.  
Let's address the image carousel issue fixed in a separate pull request.

**Review by intisarosman1 — APPROVED** [review]
I can see the images (though they don't swipe). So far, so good!

**Review by JoyZhang2023 — APPROVED** [review]
What a chore. All images are copied and named in the same order as original site. Thank you!

**Pull request merged**
