### PR TITLE
PelletierConstructionGroup.github.io_5_10-01_Houzz-assets-removal

### LINKED ISSUE #10: Remove houzz assets and css styles: inside project folder
Related to #2 

As a developer, I will want to remove houzz assets and styles from the following files:
projects/

- [x] 6871458-great-wall-of-lake-city.html
- [x] 7167805-composite-deck.html

### PR DESCRIPTION
**Pull request by JoyZhang2023**
Resolves #10  Remove Houzz assets from below file

- [x] projects/6871458-great-wall-of-lake-city.html
- [x] projects/7167805-composite-deck.html

This pr is to remove Houzz social media logo/link and "Created with Houzz" logo/link from footer section
image

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
All Houzz logos have been removed.

**Review by BradleyCharles — APPROVED** [review]
Pages look good. Logos gone!

**Review by Seiyaroo — APPROVED** [review]
LGTM! We should get our linter under control, I think thats the cause of the huge diffs being shown.

**Review by IsaacJrTypes — APPROVED** [review]
Great Job! All Houszz logos have been removed on great-wall-of-lake-city and composit-deck.html
CleanShot 2024-05-06 at 14 18 29@2x
CleanShot 2024-05-06 at 14 18 03@2x

One thing I did notice is that you don't have commit signatures which will cause merging issues in the future. Look into verifying your github account with a GPG key. https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification 
If you are on windows, there is a setup guide on the web practicum's reference section on canvas.

**Pull request merged**
