### PR TITLE
PelletierConstructionGroup-6-39-copy-javascript-from-houzz-contactspage

### LINKED ISSUE #39: Copy JavaScript from Houzz: contact.html

### PR DESCRIPTION
**Pull request by Ali-7s**
Resolves #39 
* Updated JavaScript src links in contacts.html

### CODE REVIEW

**Review by taylorpapke — APPROVED** [review]
Links appear to be correct. As you mentioned in @JoyZhang2023's PR, page css is rendering different for contact and index pages but is coming from the main branch.

**Review by heosman — APPROVED** [review]
LGTM, styles on this page looks like main's.

**Review by JoyZhang2023 — APPROVED** [review]
LGTM. All scripts have been replaced with local js file.

**Review by IsaacJrTypes — APPROVED** [review]
Javascript files are updated and looks like the CSS issues stem from a different area since main has the same CSS issues.

**Pull request merged**
