### PR TITLE
PelletierConstructionGroup.github.io_6_43_replace-contact-form

### LINKED ISSUE #43: Contact Page Form: Replace contact form with Google form
As a developer, I will want to replace the current contact form with a Google form.

Tasks:
- [x] [Create Google form based on current contact form. ](https://forms.gle/N7myENfPkhxGYhyn8)
- [x] Replace current contact form with embedded Google form.

Related to #42

### PR DESCRIPTION
**Pull request by heosman**
Resolves #43 

This PR replaces the current contact form on the contact.html page with a Google form. I created the Google form based on the contact form and then embedded the form using the iframe. Not much styling was needed other than changing the width and height of the form to fit the page. Also, the form is functional, but set to send to my email at the moment.

image

Related to #42

### CODE REVIEW

**Review by larsswenson — COMMENTED** [review]
Well done! Looks great and functions as expected.

**Review by IsaacJrTypes — APPROVED** [review]
I was able to successfully submit the contact form. There is some minor css issues like large empty space after request. I see that the iframe height is hardcoded so the initial iframe renders without scrolling. Functionally, it works well. Great job!
CleanShot 2024-05-15 at 14 44 33@2x

**Comment by taylorpapke** [comment]
> Well done! Looks great and functions as expected.

@larsswenson Can you approve if it looks good on your end?

**Review by JoyZhang2023 — APPROVED** [review]
Page renders fine and Google form works properly with submission and clear. Good job!

**Comment by taylorpapke** [comment]
@Seiyaroo Can you look this over when you get a chance and provide feedback?

**Review by Seiyaroo — APPROVED** [review]
LGTM, seems to fit the same way as old one. Thanks Hanan!

**Pull request merged**
