### PR TITLE
I will update the project website

### PR DESCRIPTION
**Pull request by ogarmela**
issue #8

### CODE REVIEW

**Review by larsswenson — COMMENTED** [review]
When I opened this file, all of the houzz logos and links still remain.

**Comment by taylorpapke** [comment]
I am also still seeing the Houzz logos:
Screenshot 2024-04-30 at 9 07 02 PM

**Review by taylorpapke — COMMENTED** [review]
7167820-new-shop.html looks good but I'm still seeing the Houzz logos on 7167828-bathroom.html

**Comment by taylorpapke** [comment]
@ogarmela I sent you a DM in regard to the closure of this PR. @larsswenson will readdress this in a new PR soon.

**Pull request closed without merging**
